#!/bin/expect -f
log_user 1
set timeout -1
proc Test { command errorMessage error expected } {
    send_user "TEST-Client3----------$command----Expecting- $expected\n"
    send $command\r
    expect {
        -re BROADCAST*{
         expect {
         -re $expected* { if { [string match "ACK*" $expected ] } { if {[string match "*REQUEST rent*" $command ] || [ string match "REQUEST return*" $command ] || [ string match "REQUEST addmovie*" $command ] || [ string match "REQUEST remmovie*" $command ] || [ string match "REQUEST changeprice*" $command ] } {
                    send_user "TEST------expecting BROADCAST...\n"
                    expect {
                        -re BROADCAST* { send_user "TEST----------success\n"}
                        }
                    } else { send_user "TEST----------success\n"}
            } else { send_user "TEST----------success\n"}
        }
        -re $error* {send_user "TEST----------failed: $errorMessage\n"; exit 1}
        eof {exit 0}
    }
        }
         -re $expected* { if { [string match "ACK*" $expected ] } { if {[string match "*REQUEST rent*" $command ] || [ string match "REQUEST return*" $command ] || [ string match "REQUEST addmovie*" $command ] || [ string match "REQUEST remmovie*" $command ] || [ string match "REQUEST changeprice*" $command ] } {
                    send_user "TEST------expecting BROADCAST...\n"
                    expect {
                        -re BROADCAST* { send_user "TEST----------success\n"}
                        }
                    } else { send_user "TEST----------success\n"}
            } else { send_user "TEST----------success\n"}
        }
        -re $error* {send_user "TEST----------failed: $errorMessage\n"; exit 1}
        eof {exit 0}
    }
}
spawn bin/BBclient 127.0.0.1 7777
Test "REQUEST return \"dont care\"" "not loggedin" "ACK" "ERROR request return failed"
Test "REQUEST balance info" "not loggedin" "ACK" "ERROR request balance failed"
Test "REQUEST balance add" "not loggedin" "ACK" "ERROR request balance failed"
Test "SIGNOUT" "not loggedin" "ACK" "ERROR signout failed"
Test "LOGIN guy amit" "user does not exists" "ACK" "ERROR login failed"
Test "REGISTER client3 client3 country=\"israel\"" "should be successful" "ERROR" "ACK registration succeeded"
Test "LOGIN client3 client3" "should be successful" "ERROR" "ACK login succeeded"
Test "REQUEST balance add 1000" "should be successful" "ERROR" "ACK balance 1000 added 1000"
Test "REQUEST rent \"movie1\"" "banned country" "ACK" "ERROR request rent failed"
#send "REQUEST rent \"movie2\"" ;#"should be successful" "ERROR" "ACK rent "movie2" success -dont care"
#send "REQUEST rent \"movie3\"" ;#-only one copy and two trying to rent -dont care -dont care
Test "SIGNOUT" "should be successful" "ERROR" "ACK signout succeeded"
